### ISSUE TITLE
Could not pass event EntityDeathEvent to Adapt

### ISSUE THREAD

**Issue by InternetVet** [VolmitSoftware/Adapt#161]
### Problem

Randomly while the server is running this happens: 

[20:44:11] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Adapt v1.1.7-1.19.2
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
	at com.volmit.adapt.api.world.AdaptServer.offer(AdaptServer.java:77) ~[Adapt-1.1.7-1.19.2.jar:?]
	at com.volmit.adapt.api.xp.XP.spatialXP(XP.java:49) ~[Adapt-1.1.7-1.19.2.jar:?]
	at com.volmit.adapt.api.skill.Skill.xp(Skill.java:131) ~[Adapt-1.1.7-1.19.2.jar:?]
	at com.volmit.adapt.content.skill.SkillHunter.on(SkillHunter.java:114) ~[Adapt-1.1.7-1.19.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-119]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
	at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:405) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2067) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2982) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2909) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1464) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-119]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-119]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:44:12] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Adapt v1.1.7-1.19.2
java.lang.ArrayIndexOutOfBoundsException: null
[20:44:13] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Adapt v1.1.7-1.19.2
java.lang.ArrayIndexOutOfBoundsException: null
[20:44:13] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Adapt v1.1.7-1.19.2
java.lang.ArrayIndexOutOfBoundsException: null

and it keeps repeating until restart...

Can't seem to find a fix

### Minecraft Version

1.19

### Adapt Version

1.1.7

### Log

https://pastebin.com/kx5wraWN

**Comment by NextdoorPsycho** [comment]
What are you doing to cause this?

**Comment by InternetVet** [comment]
I kill Endermen in the end using my sword, then this spams

**Comment by NextdoorPsycho** [comment]
> I kill Endermen using an exp grinder method in the end, then this spams as i mass kill them with a sword.

um, are you on discord?
I can send you a jar to test if you would be willing

**Comment by InternetVet** [comment]
Could we use teamspeak by chance? i have file browser for upload of the jar there too if thats not too big of a hassle
