### ISSUE TITLE
NullPointerException on disabling with WanderingTraders

### ISSUE THREAD

**Issue by KNNI** [VolmitSoftware/Adapt#174]
### Problem

1. Install Wandering Traders (https://www.spigotmc.org/resources/wandering-trades-easily-customize-wandering-traders-1-16-1-19.79068/) and Adapt (https://www.spigotmc.org/resources/adapt-leveling-skills-and-abilities.103790)
2. Start Server
3. Stop Server
4. See this Error:

```
[12:35:04] [Server thread/INFO]: [Adapt] Disabling Adapt v1.2.1-1.19.2
[12:35:04] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "xyz.jpenilla.wanderingtrades.lib.cloud.commandframework.CommandTree$Node.getValue()" because the return value of "xyz.jpenilla.wanderingtrades.lib.cloud.commandframework.bukkit.BukkitCommand.namedNode()" is null
[12:35:04] [Server thread/WARN]: 	at WanderingTrades-1.7.3.jar//xyz.jpenilla.wanderingtrades.lib.cloud.commandframework.bukkit.BukkitCommand.getUsage(BukkitCommand.java:200)
[12:35:04] [Server thread/WARN]: 	at Adapt-1.2.1-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.unregisterCommand(VolmitPlugin.java:492)
[12:35:04] [Server thread/WARN]: 	at Adapt-1.2.1-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.unregisterCommands(VolmitPlugin.java:543)
[12:35:04] [Server thread/WARN]: 	at Adapt-1.2.1-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.unregisterAll(VolmitPlugin.java:78)
[12:35:04] [Server thread/WARN]: 	at Adapt-1.2.1-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.onDisable(VolmitPlugin.java:239)
[12:35:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[12:35:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[12:35:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579)
[12:35:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556)
[12:35:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499)
[12:35:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.s(MinecraftServer.java:933)
[12:35:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.s(DedicatedServer.java:781)
[12:35:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1232)
[12:35:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[12:35:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:35:04] [Server thread/INFO]: Saving players
[12:35:04] [Server thread/INFO]: Saving worlds
```

### Minecraft Version

1.19

### Adapt Version

Latest :^ (v1.2.1-1.19.2)

### Log

https://pastebin.com/TyCM3SfJ

**Comment by NextdoorPsycho** [comment]
I need a Full log @KNNI 
Not a Snippet

**Comment by KNNI** [comment]
Complete: https://mclo.gs/RAvIBfQ
without Adapt: https://mclo.gs/2bHfGqq
without WanderingTrades: https://mclo.gs/WKJn8NO

ur welcome.

**Comment by NextdoorPsycho** [comment]
This is an issue with  **WanderingTrades**
[21:10:35 INFO]: [WanderingTrades] Successfully registered Mojang Brigadier support for commands.
[21:10:35 INFO]: [WanderingTrades] Successfully registered asynchronous command completion listener.

They are listening to Brig/Command calls on shutdown. Adapt uses those, and we terminate them when we're done. This is not on our end, they need to not do that. There is nothing i can do but Rewrite Mortar, Our command handeler and the whole framework of Adapt for commands and listeners (im not going to do that) when they could just not try and do something on the onDisable method that involves other plugins

**Comment by KNNI** [comment]
Sorry to reopen this issue, but jpenilla says it's probably Adapt after all. Can we reopen the case?
(https://github.com/jpenilla/WanderingTrades/issues/148)

**Comment by NextdoorPsycho** [comment]
The error is on shutdown, and is just complaining about the Command structure, My only fic is to ignore the Exception, but if you look at the error, its from their interaction. so me hiding it would still cause the error to be spat out probably. 

Its Benign, and everything works, other than an error when the server is closing. This is not something ill Fix when we aren't doing anything wrong really.  And to be fair neither are they, we just have plugin interactions that are problematic on shutdown. but no ACTUAL problems are happening from this, just command un-registration problems. Probably X was already disabled by Adapt or vice versa. Either way i cant stop this problem from happening without changing out command system, and there is no real problem here as everything is disabled in the end.
