### ISSUE TITLE
NullPointerException when disabling Advancements

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#209]
### Problem

Disable advancements and... level skills? idk

```
[16:19:49 WARN]: java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.util.advancements.advancement.Advancement.displayToast(org.bukkit.entity.Player)" because the return value of "java.util.Map.get(Object)" is null
[16:19:49 WARN]:        at Adapt-1.3.5-1.19.2.jar//com.volmit.adapt.api.world.AdvancementHandler.grant(AdvancementHandler.java:84)
[16:19:49 WARN]:        at Adapt-1.3.5-1.19.2.jar//com.volmit.adapt.api.world.AdvancementHandler.grant(AdvancementHandler.java:90)
[16:19:49 WARN]:        at Adapt-1.3.5-1.19.2.jar//com.volmit.adapt.api.skill.Skill.checkStatTrackers(Skill.java:82)
[16:19:49 WARN]:        at Adapt-1.3.5-1.19.2.jar//com.volmit.adapt.content.skill.SkillAgility.onTick(SkillAgility.java:112)
[16:19:49 WARN]:        at Adapt-1.3.5-1.19.2.jar//com.volmit.adapt.api.tick.TickedObject.tick(TickedObject.java:116)
[16:19:49 WARN]:        at Adapt-1.3.5-1.19.2.jar//com.volmit.adapt.api.tick.Ticker.lambda$tick$1(Ticker.java:73)
[16:19:49 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:19:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:19:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:19:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:19:49 WARN]: [Adapt] Task #69560 for Adapt v1.3.5-1.19.2 generated an exception
java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.util.advancements.advancement.Advancement.getProgress(org.bukkit.entity.Player)" because "<parameter2>" is null
        at com.volmit.adapt.util.advancements.manager.AdvancementManager.grantAdvancement(AdvancementManager.java:468) ~[Adapt-1.3.5-1.19.2.jar:?]
        at com.volmit.adapt.api.world.AdvancementHandler.lambda$grant$2(AdvancementHandler.java:80) ~[Adapt-1.3.5-1.19.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-145]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-145]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Minecraft Version

1.19.2

### Adapt Version

1.3.5-1.19.2

### Log

https://mclo.gs/2lHX2of

**Comment by NextdoorPsycho** [comment]
oops i missed up a not-check
My bad, Thanks for the report
