### ISSUE TITLE
Error msg when restarting server automatically 

### ISSUE THREAD

**Issue by InternetVet** [VolmitSoftware/Adapt#229]
### Problem

I installed then newest update and got this on restart. 

[15:40:22 WARN]: java.lang.NullPointerException: Cannot invoke "net.frankheijden.serverutils.dependencies.cloud.CommandTree$Node.getValue()" because the return value of "net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.namedNode()" is null
[15:40:22 WARN]:        at ServerUtils-Bukkit-3.5.3.jar//net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.getUsage(BukkitCommand.java:200)
[15:40:22 WARN]:        at Adapt-1.3.7-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.unregisterCommand(VolmitPlugin.java:492)
[15:40:22 WARN]:        at Adapt-1.3.7-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.unregisterCommands(VolmitPlugin.java:543)
[15:40:22 WARN]:        at Adapt-1.3.7-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.unregisterAll(VolmitPlugin.java:78)
[15:40:22 WARN]:        at Adapt-1.3.7-1.19.2.jar//com.volmit.adapt.util.VolmitPlugin.onDisable(VolmitPlugin.java:239)
[15:40:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[15:40:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[15:40:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579)
[15:40:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556)
[15:40:22 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499)
[15:40:22 WARN]:        at net.minecraft.server.MinecraftServer.s(MinecraftServer.java:933)
[15:40:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.s(DedicatedServer.java:781)
[15:40:22 WARN]:        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:888)
[15:40:22 WARN]:        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92)
[15:40:22 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61)
[15:40:22 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[15:40:22 WARN]:        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
[15:40:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[15:40:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[15:40:22 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1417)
[15:40:22 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1193)
[15:40:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[15:40:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

Nothing else though ;/

### Minecraft Version

1.19.2

### Adapt Version

1.3.7

### Log

https://prnt.sc/d39PrRiFhCf6

**Comment by NextdoorPsycho** [comment]
This is not a bug in Adapt. This is when another plugin unloads ALL commands or Adapt's commands, BEFORE adapt. Adapt is unloading ALL Command Nodes with Adapt ID's, If another plugin is unloading all or some of these nodes, it will cause this error. This is on shutdown however, so it's not a big deal. I made an exception for this and ill push it in the next update, let me know if it persists
