### ISSUE TITLE
Exception encountered in Adapt Workgroup 2

### ISSUE THREAD

**Issue by mrfloris** [VolmitSoftware/Adapt#286]
### Problem

Fresh install of paper + adapt, cmi, vault, cmilib.
I did a /stop and started the server again.

Joined the game, gave myself a few chests and opened them a few times. 

Went to console, saw the exception error.

### Solution (if any)

no idea

### Minecraft Version

1.19.2

### Adapt Version

1.4.4-1.19.2

### Log

https://paste.md-5.net/omoxowotud.md

**Comment by NextdoorPsycho** [comment]
I need a full log!!!
And I'm not aroused CMI is causing problems

**Comment by mrfloris** [comment]
There isn't much more to share as a log. There's no issues during the startup, and this is all there is to it, after this I came here and posted it, and did a /stop. 

I don't understand what you mean with "aroused", .. CMI is only used to quickly give chests, it was seconds before that. I doubt it has anything to do with this exception.

**Comment by mrfloris** [comment]
Okay, I am back. i fresh installed paper, threw adapt on there again, did NOT include cmilib or cmi, or anything like that. Logged in and didn't do anything, looked at console and saw the msg. 

```
[18:16:05 INFO]: Running delayed init tasks
[18:16:05 INFO]: Done (2.459s)! For help, type "help"
[18:16:05 INFO]: Timings Reset
[18:16:05 WARN]: [PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.4.49 which is not a depend or softdepend of this plugin.
[18:16:05 INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms [5.1-R2]
[18:16:05 INFO]: 1 placeholder hook(s) registered!
[18:16:43 INFO]: UUID of player mrfloris is 631e3896-da2a-4077-974b-d047859d76bc
[18:16:43 WARN]: java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.api.world.AdaptPlayer.getData()" because the return value of "com.volmit.adapt.api.adaptation.Adaptation.getPlayer(org.bukkit.entity.Player)" is null
[18:16:43 WARN]: 	at Adapt-1.4.4-1.19.2.jar//com.volmit.adapt.api.adaptation.Adaptation.getLevel(Adaptation.java:218)
[18:16:43 WARN]: 	at Adapt-1.4.4-1.19.2.jar//com.volmit.adapt.content.adaptation.agility.AgilityWallJump.onTick(AgilityWallJump.java:95)
[18:16:43 WARN]: 	at Adapt-1.4.4-1.19.2.jar//com.volmit.adapt.api.tick.TickedObject.tick(TickedObject.java:116)
[18:16:43 WARN]: 	at Adapt-1.4.4-1.19.2.jar//com.volmit.adapt.api.tick.Ticker.lambda$tick$1(Ticker.java:73)
[18:16:43 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[18:16:43 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[18:16:43 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[18:16:43 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[18:16:43 INFO]: mrfloris joined the game
[18:16:43 INFO]: mrfloris[/127.0.0.1:62798] logged in with entity id 50 at ([world]1014.7237621029465, 67.0, -877.3772580869494)
[18:16:45 INFO]: [Adapt]: Failed to grant advancement skill_discovery Reattaching!
> pl
[18:17:11 INFO]: Plugins (5): Adapt, LuckPerms, PlaceholderAPI, spark, Vault
>
```

**Comment by NextdoorPsycho** [comment]
a few things:
**aroused** is my way of saying i dislike CMI in a funny way. its great a d the developer is fantastic, its just annoying to deal with at times. 

I Ask for a FULL LOG for numerous reasons. Despite this you have STILL not provided one. I need to see everything from the purpur version to the JVM args and everything in between. it makes my life SOOOO much wasier to be able to problem solve if you are on some like ancient non-updated fork of Tuinity's dead branch of a merge... and so on. And i mark as plugin incompatibility  BeCaUsE i DonT knOw WhaT pLugIns yOU hAVe, And A fUlL lOg wOUld hAve Told ME tHAt. So i just assume you are on like some kind of Geyser/Floodgate/Citizens system

Ill look into it, but i need you to send me a full log man

**Comment by NextdoorPsycho** [comment]
I think i found the issue, containers were giving 300X more Xp than they should and sequencing that, but they were not and too fast giving XP. a thread probably spin up at the same time so now im fixing that. should nolonger see this in the next update

Thanks for the report

**Comment by mrfloris** [comment]
I am sorry, but you have a pretty aggressive undertone to the way you talk to those who report potential issues as a courtesy. 

I am more than willing to help where I can, but I am less inclined to do so if doing so means being talked down to. 

The form asks prior to submitting a report the version of adapt, and the server info. My paste link includes the info in there as well:
```
> ver Adapt
[08:20:02 INFO]: Adapt version 1.4.4-1.19.2
[08:20:02 INFO]: Authors: NextdoorPsycho, Cyberpwn and Vatuu
> ver
[08:20:03 INFO]: Checking version, please wait...
[08:20:03 INFO]: This server is running Paper version git-Paper-211 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eb68bd4)
You are running the latest version
Previous version: git-Paper-207 (MC: 1.19.2)
>
```
Which would have told you it's directly from Paper, the latest build of that day, I did inform you there are no startup issues, and that it was a fresh installation. And I've provided as much information as I am comfortable sharing. Including the list of plugins when you asked for additional information. 

The "fULl lOg" would not have shown the startup parameters for the JVM, you didn't ask for this either. And it just shows the worlds being prepared and the plugins loading without any warnings. Any warning/error I've included in the pastebins, which were after 'Done.' 

Aroused here means sexual excitement as well. Just so you know. But that's not important, it just confused me at the time. I understand your dislike for other plugins now. Disclaimer, by the way, I am an admin on CMI's discord server ~ to put things in perspective.

Thank you for realising in the end that this bug was indeed unrelated to CMI and actually an issue with Adapt itself. I appreciate it really that you looked into it - and thank you for releasing a patch on SpigotMC earlier. However please, moving forward, be mindful of how it can come across how you say certain things as it felt rather aggressive and as if you were talking down to me, something I didn't appreciate. 

Anyway, here's the full log of one of the sessions; <https://paste.md-5.net/uwegofosoy.md>
