### ISSUE TITLE
 Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by keaizhu** [VolmitSoftware/Adapt#366]
### Problem

When a player enters the game, 
Count not pass event PlayerJoinEvent to Adapt v1.5.0-1.19.3

Then the console starts to screen
[16:12:29] [Adapt Workgroup 12/WARN]: java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.api.world.AdaptPlayer.getData()" because the return value of "com.volmit.adapt.api.adaptation.Adaptation.getPlayer(org.bukkit.entity.Player)" is null
[16:12:29] [Adapt Workgroup 12/WARN]: 	at Adapt-1.5.0-1.19.3.jar//com.volmit.adapt.api.adaptation.Adaptation.getLevel(Adaptation.java:239)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at Adapt-1.5.0-1.19.3.jar//com.volmit.adapt.content.adaptation.agility.AgilityWallJump.onTick(AgilityWallJump.java:95)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at Adapt-1.5.0-1.19.3.jar//com.volmit.adapt.api.tick.TickedObject.tick(TickedObject.java:116)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at Adapt-1.5.0-1.19.3.jar//com.volmit.adapt.api.tick.Ticker.lambda$tick$1(Ticker.java:73)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:12:29] [Adapt Workgroup 12/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

I don't know whether I have expressed clearly. If you need any additional information, please tell me. Thank you

### Minecraft Version

1.19.2

### Adapt Version

1.5.0

### Log

https://mclo.gs/UbBtVxP

**Comment by NextdoorPsycho** [comment]
Update your purpur to 1.19.2 or actually send mean log where it was 1.19.2. 

Invalid

**Comment by keaizhu** [comment]
In purpur 1.19.2, the situation is exactly the same, without the influence of other plugins，This is log，Thanks
https://mclo.gs/Uw3JI5t

**Comment by NextdoorPsycho** [comment]
Are you reading anything that you're downloading, or are you just downloading things and putting them on your server?

currently adapt is version dependent like all of our plug-ins. You are installing a 1.19.3 version of adapt on a 1.19.2 version of the game. 

and prior you had it on a 1.19 version. 

tell me, do you see the issue here? 
if you're going to a non latest game version, use the plug-in that uses the said version

if you're still having issues after that, feel free to let me know.

**Comment by NextdoorPsycho** [comment]
Once we've gotten things to actually properly load if there's any more issues, make a new issue request

**Comment by keaizhu** [comment]
Oh, this is my question. I'm sorry to bother you.  I really didn't notice the version restrictions.Thank you for your answer.
