### ISSUE TITLE
Players are sometimes unable to enter the game

### ISSUE THREAD

**Issue by 1983378984** [VolmitSoftware/Adapt#369]
### Problem

I found on the server that some players enter and exit, this is the error seen in the background
[17:49:23 WARN]: java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.api.world.AdaptPlayer.getData()" because the return value of "com.volmit.adapt.api.adaptation.Adaptation.getPlayer(org.bukkit.entity.Player)" is null
[17:49:23 WARN]:        at Adapt-1.4.20-1.19.2.jar//com.volmit.adapt.api.adaptation.Adaptation.getLevel(Adaptation.java:239)
[17:49:23 WARN]:        at Adapt-1.4.20-1.19.2.jar//com.volmit.adapt.api.adaptation.Adaptation.hasAdaptation(Adaptation.java:196)
[17:49:23 WARN]:        at Adapt-1.4.20-1.19.2.jar//com.volmit.adapt.content.adaptation.blocking.BlockingMultiArmor.on(BlockingMultiArmor.java:128)
[17:49:23 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor569.execute(Unknown Source)
[17:49:23 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[17:49:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[17:49:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:49:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:677)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.drop(EntityHuman.java:810)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:757)
[17:49:23 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:2349)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:751)
[17:49:23 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:729)
[17:49:23 WARN]:        at net.minecraft.world.inventory.ContainerPlayer.b(ContainerPlayer.java:158)
[17:49:23 WARN]:        at net.minecraft.server.level.EntityPlayer.r(EntityPlayer.java:1652)
[17:49:23 WARN]:        at net.minecraft.server.level.EntityPlayer.closeContainer(EntityPlayer.java:1636)
[17:49:23 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:550)
[17:49:23 WARN]:        at net.minecraft.server.level.WorldServer$a.f(WorldServer.java:2681)
[17:49:23 WARN]:        at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:2571)
[17:49:23 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.f(PersistentEntitySectionManager.java:232)
[17:49:23 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager$a.a(PersistentEntitySectionManager.java:623)
[17:49:23 WARN]:        at net.minecraft.world.entity.Entity.b(Entity.java:4462)
[17:49:23 WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:704)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1539)
[17:49:23 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1572)
[17:49:23 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:669)
[17:49:23 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:606)
[17:49:23 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2112)
[17:49:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2092)
[17:49:23 WARN]:        at net.minecraft.network.NetworkManager.m(NetworkManager.java:765)
[17:49:23 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:252)
[17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1609)
[17:49:23 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
[17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1441)
[17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1208)
[17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[17:49:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:49:23 WARN]: java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.api.world.AdaptPlayer.getData()" because the return value of "com.volmit.adapt.api.adaptation.Adaptation.getPlayer(org.bukkit.entity.Player)" is null
[17:49:23 WARN]:        at Adapt-1.4.20-1.19.2.jar//com.volmit.adapt.api.adaptation.Adaptation.getLevel(Adaptation.java:239)
[17:49:23 WARN]:        at Adapt-1.4.20-1.19.2.jar//com.volmit.adapt.api.adaptation.Adaptation.hasAdaptation(Adaptation.java:196)
[17:49:23 WARN]:        at Adapt-1.4.20-1.19.2.jar//com.volmit.adapt.content.adaptation.excavation.ExcavationOmniTool.on(ExcavationOmniTool.java:181)
[17:49:23 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor676.execute(Unknown Source)
[17:49:23 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[17:49:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[17:49:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:49:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:677)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.drop(EntityHuman.java:810)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:757)
[17:49:23 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:2349)
[17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:751)
[17:49:23 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:729)
[17:49:23 WARN]:        at net.minecraft.world.inventory.ContainerPlayer.b(ContainerPlayer.java:158)
[17:49:23 WARN]:        at net.minecraft.server.level.EntityPlayer.r(EntityPlayer.java:1652)
[17:49:23 WARN]:        at net.minecraft.server.level.EntityPlayer.closeContainer(EntityPlayer.java:1636)
[17:49:23 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:550)
[17:49:23 WARN]:        at net.minecraft.server.level.WorldServer$a.f(WorldServer.java:2681)
[17:49:23 WARN]:        at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:2571)
[17:49:23 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.f(PersistentEntitySectionManager.java:232)
[17:49:23 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager$a.a(PersistentEntitySectionManager.java:623)

### Minecraft Version

1.19.2

### Adapt Version

1.4.20

### Log

[17:49:23 WARN]:        at net.minecraft.world.entity.Entity.b(Entity.java:4462) [17:49:23 WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:704) [17:49:23 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1539) [17:49:23 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1572) [17:49:23 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:669) [17:49:23 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:606) [17:49:23 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2112) [17:49:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2092) [17:49:23 WARN]:        at net.minecraft.network.NetworkManager.m(NetworkManager.java:765) [17:49:23 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:252) [17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1609) [17:49:23 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485) [17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1441) [17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1208) [17:49:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) [17:49:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NextdoorPsycho** [comment]
This is not a log not will I help you until you format this property. Join the discord Ave typo /log make a new issue and provide me with what I need
