### ISSUE TITLE
tab-comple command server console reports error

### ISSUE THREAD

**Issue by ProjectSky** [VolmitSoftware/Adapt#376]
### Problem

* use ```/ada o gui *``` press tab
* ```* = any string```

```
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/ada o gui s' in plugin Adapt v1.5.1-1.19.3
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabCompleteCommand(CraftServer.java:2270) ~[paper-1.19.3.jar:git-Paper-375]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabComplete(CraftServer.java:2242) ~[paper-1.19.3.jar:git-Paper-375]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[paper-1.19.3.jar:git-Paper-375]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Paper-375]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[paper-1.19.3.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[paper-1.19.3.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:901) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-375]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-375]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.api.skill.Skill.getAdaptations()" because "skillObj" is null
        at com.volmit.adapt.commands.openGui.CommandOpenGUI.addTabOptions(CommandOpenGUI.java:112) ~[Adapt-1.5.1-1.19.3.jar:?]
        at com.volmit.adapt.util.MortarCommand.handleTab(MortarCommand.java:67) ~[Adapt-1.5.1-1.19.3.jar:?]
        at com.volmit.adapt.util.VirtualCommand.hitTab(VirtualCommand.java:162) ~[Adapt-1.5.1-1.19.3.jar:?]
        at com.volmit.adapt.util.VirtualCommand.hitTab(VirtualCommand.java:150) ~[Adapt-1.5.1-1.19.3.jar:?]
        at com.volmit.adapt.util.VirtualCommand.hitTab(VirtualCommand.java:150) ~[Adapt-1.5.1-1.19.3.jar:?]
        at com.volmit.adapt.util.VolmitPlugin.onTabComplete(VolmitPlugin.java:408) ~[Adapt-1.5.1-1.19.3.jar:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

### Minecraft Version

1.19.2

### Adapt Version

LATEST

### Log

https://mclo.gs/u5J6Jla

**Comment by NextdoorPsycho** [comment]
Fixed
