### ISSUE TITLE
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by mclk623** [VolmitSoftware/Adapt#432]
### Problem

1. Install Adapt...
2. Install Residence with CMIlib...
3. create a Residence land Stay in the land
4. Observe the error...
[08:03:21 WARN]: java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
[08:03:21 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[08:03:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[08:03:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[08:03:21 WARN]:        at Residence5.1.1.3.jar//com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:169)
[08:03:21 WARN]:        at Residence5.1.1.3.jar//com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:88)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.content.protector.ResidenceProtector.checkPerm(ResidenceProtector.java:69)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.content.protector.ResidenceProtector.checkRegion(ResidenceProtector.java:22)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.api.adaptation.Adaptation.lambda$checkRegion$9(Adaptation.java:223)
[08:03:21 WARN]:        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[08:03:21 WARN]:        at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1932)
[08:03:21 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[08:03:21 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[08:03:21 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[08:03:21 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[08:03:21 WARN]:        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[08:03:21 WARN]:        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[08:03:21 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[08:03:21 WARN]:        at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.api.adaptation.Adaptation.checkRegion(Adaptation.java:223)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.api.adaptation.Adaptation.hasAdaptation(Adaptation.java:244)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.content.adaptation.discovery.DiscoveryArmor.onTick(DiscoveryArmor.java:112)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.api.tick.TickedObject.tick(TickedObject.java:116)
[08:03:21 WARN]:        at Adapt-1.10.0-1.19.4.jar//com.volmit.adapt.api.tick.Ticker.lambda$tick$1(Ticker.java:86)
[08:03:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[08:03:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[08:03:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[08:03:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)

### Minecraft Version

1.19.2

### Adapt Version

1.10.0

### Log

https://pastebin.com/DpUGepgM

**Comment by NextdoorPsycho** [comment]
Hello! i see this, and ill see if i can get a fix out!

**Comment by NextdoorPsycho** [comment]
@mclk623  Are you on discord? i can give you a copy to try and make sure it works if you are available!

**Comment by mclk623** [comment]
yeah  I have

**Comment by hectozul** [comment]
Is this related with the same issue reported here?
![image](https://github.com/VolmitSoftware/Adapt/assets/70169870/ac2a83bb-43a2-4e9e-bf66-eba2f3a5361f)
Using adapt latest version Adapt-1.10.1-1.19.4.

**Comment by NextdoorPsycho** [comment]
should be fixed on latest
